language: node_js

node_js:
  - "0.11"
  - "4"
  - "5"
  - "6"

before_script:
  - npm link

addons:
  code_climate:
    repo_token: ccfbd3752b347fc937272cc69dabbdd88074847c0b03f54464027a7a8108e1d1

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
